name: ci
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build shadowJar --stacktrace --parallel

      - name: Upload Jar
        uses: actions/upload-artifact@v2.3.1
        with:
          name: TranslationTemplateGenerator
          retention-days: 30
          path: |
            ./TranslationTemplateGenerator/build/libs/*.jar

